version: MultiClassSVDD
description: MultiClassSVDD
time_version: False # if set ture, add time information in version
save_version_files: False # if set true, save each version files in runs
save_version_file_patterns:
  - "*.py"
  - "*.yaml"
pass_dirs:
  - '.'
  - '_'
  - 'runs'
  - 'results'

# filepath
train_dirs:
  - ../data/dataset/fan/train
  #- ../data/dataset/pump/train
  #- ../data/dataset/slider/train
  #- ../data/dataset/valve/train
  #- ../data/dataset/ToyCar/train
  #- ../data/dataset/ToyConveyor/train
add_dirs:
  - ../data/eval_dataset/fan/train
  #- ../data/eval_dataset/pump/train
  #- ../data/eval_dataset/slider/train
  #- ../data/eval_dataset/valve/train
  #- ../data/eval_dataset/ToyCar/train
  #- ../data/eval_dataset/ToyConveyor/train
valid_dirs:
  - ../data/dataset/fan/test
  #- ../data/dataset/pump/test
  #- ../data/dataset/slider/test
  #- ../data/dataset/valve/test
  #- ../data/dataset/ToyCar/test
  #- ../data/dataset/ToyConveyor/test
test_dirs:
  - ../data/dataset/fan/test
  #- ../data/dataset/pump/test
  #- ../data/dataset/slider/test
  #- ../data/dataset/valve/test
  #- ../data/dataset/ToyCar/test
  #- ../data/dataset/ToyConveyor/test

result_dir: ./results
# audio preprocess
sr: 16000
n_fft: 1024
n_mels: 128
win_length: 1024
hop_length: 512
power: 2.0
secs: 10

cuda: True
# train
random_seed: 42
epochs: 30
batch_size: 32
num_workers: 0
lr: 1e-4
device_ids:
  - 0
valid_every_epochs: 10
early_stop_epochs: -1
start_save_model_epochs: 1
save_model_interval_epochs: 1
start_scheduler_epoch: 20
start_valid_epoch: 0
warm_up: 1 # warm up epochs for training with machine ID


# loss
use_arcface: True
m: 0.7
s: 30
sub_center: 1

# anomaly score
gmm_n: False # if set as a int value, use gmm to fit feature for each ID and estimate anomaly score


# test
load_epoch: best # it will test your model if set a value, e.g. best, 10, 100

# data augmentation
use_augmentation: True
noise_prob: 0.3 # add noise probability
noise_snr_min_db: 15.0
noise_snr_max_db: 30.0

mixup_enable: True
mixup_alpha: 0.4
mixup_prob: 0.3